"""Initial migration with core models

Revision ID: 7c9a64bf1029
Revises: 
Create Date: 2025-11-26 03:06:21.812588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9a64bf1029'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('config_option_id', sa.Integer(), nullable=True),
    sa.Column('config_option_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('notify_on_restock', sa.Boolean(), nullable=False),
    sa.Column('notify_on_purchase', sa.Boolean(), nullable=False),
    sa.Column('notify_on_stock_low', sa.Boolean(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_configs', 'monitor_configs', ['is_active', 'product_id'], unique=False)
    op.create_index('idx_product_config', 'monitor_configs', ['product_id', 'config_option_id'], unique=False)
    op.create_index(op.f('ix_monitor_configs_product_id'), 'monitor_configs', ['product_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monitor_config_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_config_id'], ['monitor_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_status', 'notification_logs', ['status', 'created_at'], unique=False)
    op.create_index('idx_notification_type_status', 'notification_logs', ['notification_type', 'status'], unique=False)
    op.create_index(op.f('ix_notification_logs_monitor_config_id'), 'notification_logs', ['monitor_config_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_notification_type'), 'notification_logs', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    op.create_table('stock_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monitor_config_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock_control_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('change_detected', sa.Boolean(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('change_amount', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_config_id'], ['monitor_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_change_detection', 'stock_records', ['change_detected', 'change_type'], unique=False)
    op.create_index('idx_monitor_recorded', 'stock_records', ['monitor_config_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_stock_records_monitor_config_id'), 'stock_records', ['monitor_config_id'], unique=False)
    op.create_index(op.f('ix_stock_records_recorded_at'), 'stock_records', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_records_recorded_at'), table_name='stock_records')
    op.drop_index(op.f('ix_stock_records_monitor_config_id'), table_name='stock_records')
    op.drop_index('idx_monitor_recorded', table_name='stock_records')
    op.drop_index('idx_change_detection', table_name='stock_records')
    op.drop_table('stock_records')
    op.drop_index(op.f('ix_notification_logs_status'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_notification_type'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_monitor_config_id'), table_name='notification_logs')
    op.drop_index('idx_notification_type_status', table_name='notification_logs')
    op.drop_index('idx_notification_status', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_monitor_configs_product_id'), table_name='monitor_configs')
    op.drop_index('idx_product_config', table_name='monitor_configs')
    op.drop_index('idx_active_configs', table_name='monitor_configs')
    op.drop_table('monitor_configs')
    # ### end Alembic commands ###
