"""Initial migration with Website MonitorConfig StockRecord and MonitorHistory

Revision ID: f07a2071b526
Revises: 
Create Date: 2025-11-26 04:50:24.604494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f07a2071b526'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('api_identifier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('api_secret', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_is_active'), 'websites', ['is_active'], unique=False)
    op.create_index(op.f('ix_websites_name'), 'websites', ['name'], unique=False)
    op.create_table('monitor_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('threshold_low', sa.Integer(), nullable=True),
    sa.Column('threshold_high', sa.Integer(), nullable=True),
    sa.Column('notify_on_restock', sa.Boolean(), nullable=False),
    sa.Column('notify_on_purchase', sa.Boolean(), nullable=False),
    sa.Column('notify_on_threshold', sa.Boolean(), nullable=False),
    sa.Column('purchase_link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_configs_is_active'), 'monitor_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_monitor_configs_product_id'), 'monitor_configs', ['product_id'], unique=False)
    op.create_index(op.f('ix_monitor_configs_website_id'), 'monitor_configs', ['website_id'], unique=False)
    op.create_table('monitor_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_config_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('from_quantity', sa.Integer(), nullable=True),
    sa.Column('to_quantity', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('change_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('threshold_breached', sa.Boolean(), nullable=False),
    sa.Column('threshold_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('threshold_value', sa.Integer(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_config_id'], ['monitor_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monitor_histories_config_created', 'monitor_histories', ['monitor_config_id', 'created_at'], unique=False)
    op.create_index('idx_monitor_histories_event_type', 'monitor_histories', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_monitor_histories_created_at'), 'monitor_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_monitor_histories_event_type'), 'monitor_histories', ['event_type'], unique=False)
    op.create_index(op.f('ix_monitor_histories_monitor_config_id'), 'monitor_histories', ['monitor_config_id'], unique=False)
    op.create_table('stock_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_config_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('stock_control_enabled', sa.Boolean(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('change_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('threshold_breached', sa.Boolean(), nullable=False),
    sa.Column('threshold_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_config_id'], ['monitor_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_records_monitor_created', 'stock_records', ['monitor_config_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_records_created_at'), 'stock_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_records_monitor_config_id'), 'stock_records', ['monitor_config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_records_monitor_config_id'), table_name='stock_records')
    op.drop_index(op.f('ix_stock_records_created_at'), table_name='stock_records')
    op.drop_index('idx_stock_records_monitor_created', table_name='stock_records')
    op.drop_table('stock_records')
    op.drop_index(op.f('ix_monitor_histories_monitor_config_id'), table_name='monitor_histories')
    op.drop_index(op.f('ix_monitor_histories_event_type'), table_name='monitor_histories')
    op.drop_index(op.f('ix_monitor_histories_created_at'), table_name='monitor_histories')
    op.drop_index('idx_monitor_histories_event_type', table_name='monitor_histories')
    op.drop_index('idx_monitor_histories_config_created', table_name='monitor_histories')
    op.drop_table('monitor_histories')
    op.drop_index(op.f('ix_monitor_configs_website_id'), table_name='monitor_configs')
    op.drop_index(op.f('ix_monitor_configs_product_id'), table_name='monitor_configs')
    op.drop_index(op.f('ix_monitor_configs_is_active'), table_name='monitor_configs')
    op.drop_table('monitor_configs')
    op.drop_index(op.f('ix_websites_name'), table_name='websites')
    op.drop_index(op.f('ix_websites_is_active'), table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
